name: {{ENV}}

x-default-logging: &default-logging
  logging:
    driver: json-file
    options:
      max-size: "10m"
      max-file: "5"

services:
  nginx:
    image: nginx:1.27-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /srv/stack/{{ENV}}/nginx/conf.d:/etc/nginx/conf.d:ro
      - /srv/data/{{ENV}}/nginx:/var/cache/nginx
    depends_on:
      frontend:
        condition: service_started
      backend:
        condition: service_started
      keycloak:
        condition: service_started
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1"]
      interval: 30s
      timeout: 5s
      retries: 5
    <<: *default-logging
    networks:
      - app_net

  frontend:
    image: ${FRONTEND_IMAGE}
    restart: unless-stopped
    expose:
      - "8080"
    volumes:
      - /srv/data/{{ENV}}/frontend:/usr/share/nginx/html:ro
    healthcheck:
      test: ["CMD", "wget", "-q", "-O", "/dev/null", "http://127.0.0.1:8080"]
      interval: 30s
      timeout: 5s
      retries: 5
    <<: *default-logging
    networks:
      - app_net

  backend:
    image: ${BACKEND_IMAGE}
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      TZ: ${TZ}
      DB_HOST: postgres
      DB_PORT: "5432"
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -q -O /dev/null http://127.0.0.1:8080/health || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
    <<: *default-logging
    networks:
      - app_net

  keycloak:
    image: ${KEYCLOAK_IMAGE}
    command: ["start-dev", "--http-port=8080"]
    restart: unless-stopped
    expose:
      - "8080"
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/${POSTGRES_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "exec 3<>/dev/tcp/127.0.0.1/8080"]
      interval: 30s
      timeout: 5s
      retries: 10
    <<: *default-logging
    networks:
      - app_net

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    expose:
      - "5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - /srv/data/{{ENV}}/postgres:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 15s
      timeout: 5s
      retries: 8
    <<: *default-logging
    networks:
      - app_net

  mariadb:
    image: mariadb:11
    restart: unless-stopped
    expose:
      - "3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /srv/data/{{ENV}}/mariadb:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "127.0.0.1", "-u", "root", "--password=${MYSQL_ROOT_PASSWORD}"]
      interval: 20s
      timeout: 5s
      retries: 10
    <<: *default-logging
    networks:
      - app_net

networks:
  app_net:
    name: {{NETWORK_NAME}}
